// apps/web/src/app/shared/word-click-modal/word-click-modal.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  OnInit,
  signal,
} from "@angular/core";
import { DomSanitizer, SafeHtml } from "@angular/platform-browser";
import { Router } from "@angular/router";
import { ModalController } from "@ionic/angular/standalone";

import {
  IonButton,
  IonButtons,
  IonContent,
  IonIcon,
  IonItem,
  IonLabel,
  IonList,
  IonToolbar,
} from "@ionic/angular/standalone";
import { TranslatePipe } from "@ngx-translate/core";
import { addIcons } from "ionicons";
import { bookmark, bookmarkOutline, playOutline, searchOutline, volumeHighOutline } from "ionicons/icons";
import { VocabularyService } from "../../home/vocabulary/vocabulary.service";
import { MarkdownService } from "../../home/content/markdown.service";
import { DictionaryService } from "../../home/dictionary/dictionary.service";
import { type ILemma } from "../../home/dictionary/lemma/lemma.model";
import { WordLang } from "../../home/dictionary/word-lang.model";
import { SpeechSynthesizerService } from "../../home/speech-synthesizer.service";

@Component({
  selector: "app-word-click-modal",
  imports: [
    IonLabel,
    IonToolbar,
    IonButtons,
    IonButton,
    IonIcon,
    IonContent,
    IonList,
    IonItem,
    TranslatePipe,
  ],
  templateUrl: "./word-click-modal.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WordClickModalComponent implements OnInit {
  #router = inject(Router);
  #modalCtrl = inject(ModalController);
  #sanitizer = inject(DomSanitizer);
  #dictionaryService = inject(DictionaryService);
  #markdownService = inject(MarkdownService);
  #speechService = inject(SpeechSynthesizerService);

  protected vocabularyService = inject(VocabularyService);

  clickedWord = input.required<string>();
  word = input.required<string>();
  lang = input.required<string>();
  sentence = input.required<string>();
  lemmas = input.required<ILemma[]>();
  bases = input.required<string[]>();
  safeHomonyms = signal<SafeHtml[]>([]);

  protected isBookmarked = computed(() =>
    this.vocabularyService.isBookmarked(this.clickedWord(), this.lang()),
  );

  protected titleLabel = computed(() => {
    const bases = this.bases();
    const clicked = this.clickedWord();
    const basesStr = bases.join(", ");
    return bases.includes(clicked) ? basesStr : `${clicked} → ${basesStr}`;
  });

  ngOnInit() {
    // Group lemmas by homonym
    const homonymMap = new Map<string, ILemma[]>();
    for (const lemma of this.lemmas()) {
      const key = lemma.baseWord + "." + lemma.homonym;
      homonymMap.set(key, [...(homonymMap.get(key) ?? []), lemma]);
    }

    const safeHomonyms: SafeHtml[] = [];

    for (const lemmas of homonymMap.values()) {
      let first = true;
      const texts = lemmas.map((lemma) => {
        const text = lemma.text.trim();
        if (first) {
          first = false;
          return text;
        }
        // Remove redundant keyword prefix
        const regexp = new RegExp(`\\*\\*${lemma.word}\\*\\*, *(\\d+)`);
        return text.replace(regexp, "$1");
      });
      const homonymText = this.#markdownService.tinyMarkdown(
        texts.join(" ").replace(/;$/, "."),
      );

      const homonymHtml = this.#sanitizer.bypassSecurityTrustHtml(homonymText);
      safeHomonyms.push(homonymHtml);
    }

    this.safeHomonyms.set(safeHomonyms);
  }

  dictionaryLookup() {
    this.#modalCtrl.dismiss(null, "close");
    this.#router.navigate(["home/tabs/dictionary"]);
    this.#dictionaryService.lookup(new WordLang(this.word(), this.lang()));
  }

  canSpeak() {
    return this.#speechService.canSpeakLanguage(this.lang());
  }

  speakWord() {
    this.#speechService
      .speakSingle(this.clickedWord(), this.lang())
      .subscribe({ error: () => {} });
  }

  speakSentence() {
    this.#speechService
      .speakSingle(this.sentence(), this.lang())
      .subscribe({ error: () => {} });
  }

  constructor() {
    addIcons({ bookmark, bookmarkOutline, playOutline, volumeHighOutline, searchOutline });
  }
}

@if (lemmas().length === 0) {
  <div class="ion-padding">
    <ion-label>
      {{ "common.word-not-found" | translate }}
      <span class="clicked-word">{{ clickedWord() }}</span>
    </ion-label>
  </div>
} @else {
  <ion-toolbar>
    <ion-label slot="start" class="ion-padding-start clicked-word">
      {{ clickedWord() }}
    </ion-label>
    <ion-buttons slot="end">
      @if (canSpeak()) {
        <ion-button (click)="speakSentence()" [title]="'common.pronounce' | translate">
          <ion-icon
            slot="icon-only"
            name="volume-high-outline"
            [attr.aria-label]="'common.pronounce' | translate"
          ></ion-icon>
        </ion-button>
      }
      @if (!hideActions()) {
        <ion-button
          (click)="toggleQuizMode()"
          [title]="(morphologyMode.quizMode() ? 'morphology.show-breakdown' : 'morphology.quiz-breakdown') | translate"
          [attr.aria-label]="(morphologyMode.quizMode() ? 'morphology.show-breakdown' : 'morphology.quiz-breakdown') | translate"
        >
          <ion-icon
            slot="icon-only"
            [name]="morphologyMode.quizMode() ? 'school-outline' : 'eye-outline'"
          ></ion-icon>
        </ion-button>
        @if (vocabularyService.isEnabled()) {
          <ion-button
            (click)="vocabularyService.toggle(clickedWord(), lang())"
            [title]="
              (vocabularyService.currentListLocked()
                ? 'vocabulary.locked'
                : isBookmarked()
                  ? 'common.remove-bookmark'
                  : 'common.bookmark'
              ) | translate
            "
          >
            <ion-icon
              slot="icon-only"
              [name]="isBookmarked() ? 'bookmark' : 'bookmark-outline'"
              [color]="vocabularyService.currentListLocked() ? 'medium' : null"
              [attr.aria-label]="
                (vocabularyService.currentListLocked()
                  ? 'vocabulary.locked'
                  : isBookmarked()
                    ? 'common.remove-bookmark'
                    : 'common.bookmark'
                ) | translate
              "
            ></ion-icon>
          </ion-button>
        }
        <ion-button
          (click)="dictionaryLookup()"
          [title]="'common.open-entry' | translate: { word: word() }"
          [attr.aria-label]="'common.open-entry' | translate: { word: word() }"
        >
          <ion-icon slot="icon-only" name="arrow-forward-outline"></ion-icon>
        </ion-button>
      }
    </ion-buttons>
  </ion-toolbar>
  <ion-content>
    <ion-list lines="none">
      @for (h of homonyms(); track $index) {
        <ion-item>
          <ion-label>
            @if (h.breakdown && !hideActions()) {
              @if (morphologyMode.quizMode() && !revealed().has($index)) {
                <div
                  class="affix-quiz"
                  (click)="reveal($index)"
                  role="button"
                  [attr.aria-label]="
                    'morphology.reveal-prompt' | translate: { action: pointer.actionKey() | translate }
                  "
                >
                  {{
                    "morphology.reveal-prompt" | translate: { action: pointer.actionKey() | translate }
                  }}
                </div>
              } @else {
                <div class="affix-breakdown">
                  <span>{{ h.breakdown.display }}</span>
                  @if (h.breakdown.ruleNote) {
                    <ion-icon
                      class="affix-expand"
                      [name]="expanded().has($index) ? 'chevron-up-outline' : 'chevron-down-outline'"
                      (click)="toggleExpanded($index)"
                      role="button"
                      aria-label="explain"
                    ></ion-icon>
                  }
                </div>
              }
              @if (h.breakdown.ruleNote && expanded().has($index)) {
                <div class="affix-rule">
                  {{
                    "morphology.nasal-rule"
                      | translate
                        : {
                            archiphoneme: h.breakdown.ruleNote.archiphoneme,
                            surface: h.breakdown.ruleNote.surface,
                            letter: h.breakdown.ruleNote.letter
                          }
                  }}
                </div>
              }
            }
            <div [innerHTML]="h.definition" class="homonym"></div>
          </ion-label>
        </ion-item>
      }
    </ion-list>
    @if (!hideActions()) {
      <div class="resolution-hop">
        <span class="hop-link" (click)="dictionaryLookup()">→ {{ word() }}</span>
      </div>
    }
  </ion-content>
}

// apps/web-react/src/components/WordClickModal.tsx
import {
  IonButton,
  IonButtons,
  IonContent,
  IonIcon,
  IonItem,
  IonLabel,
  IonList,
  IonTitle,
  IonToolbar,
} from '@ionic/react';
import { playOutline, searchOutline, volumeHighOutline } from 'ionicons/icons';
import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { tinyMarkdown } from '../lib/markdown.ts';
import { useSpeechSynthesizer } from '../hooks/useSpeechSynthesizer.ts';
import type { ILemma } from '../types/models.ts';

interface WordClickModalProps {
  clickedWord: string;
  word: string;
  lang: string;
  sentence: string;
  lemmas: ILemma[];
  onDismiss: () => void;
  onDictionaryLookup: (word: string, lang: string) => void;
}

const WordClickModal: React.FC<WordClickModalProps> = ({
  clickedWord,
  word,
  lang,
  sentence,
  lemmas,
  onDismiss,
  onDictionaryLookup,
}) => {
  const { t } = useTranslation();
  const { speakSingle, canSpeak } = useSpeechSynthesizer();

  const homonyms = useMemo(() => {
    const homonymMap = new Map<string, ILemma[]>();
    for (const lemma of lemmas) {
      const key = lemma.baseWord + '.' + lemma.homonym;
      homonymMap.set(key, [...(homonymMap.get(key) ?? []), lemma]);
    }

    const result: string[] = [];
    for (const group of homonymMap.values()) {
      let first = true;
      const texts = group.map((lemma) => {
        const text = lemma.text.trim();
        if (first) {
          first = false;
          return text;
        }
        const regexp = new RegExp(`\\*\\*${lemma.word}\\*\\*, *(\\d+)`);
        return text.replace(regexp, '$1');
      });
      const homonymText = tinyMarkdown(
        texts.join(' ').replace(/;$/, '.'),
      );
      result.push(homonymText);
    }
    return result;
  }, [lemmas]);

  const handleDictionaryLookup = () => {
    onDismiss();
    onDictionaryLookup(word, lang);
  };

  if (lemmas.length === 0) {
    return (
      <div className="ion-padding">
        <IonLabel>
          {t('common.word-not-found')}{' '}
          <span className="clicked-word">{clickedWord}</span>
        </IonLabel>
      </div>
    );
  }

  return (
    <>
      <IonToolbar>
        <IonTitle>
          <IonLabel>
            <span className="clicked-word">{clickedWord}</span>
          </IonLabel>
        </IonTitle>
        <IonButtons slot="end">
          {canSpeak(lang) && (
            <>
              {sentence !== clickedWord && (
                <IonButton onClick={() => speakSingle(sentence, lang)}>
                  <IonIcon
                    slot="icon-only"
                    icon={playOutline}
                    aria-label="sentence"
                  />
                </IonButton>
              )}
              <IonButton onClick={() => speakSingle(clickedWord, lang)}>
                <IonIcon
                  slot="icon-only"
                  icon={volumeHighOutline}
                  aria-label="pronounce"
                />
              </IonButton>
            </>
          )}
          <IonButton onClick={handleDictionaryLookup}>
            <IonIcon
              slot="icon-only"
              icon={searchOutline}
              aria-label="lookup"
            />
          </IonButton>
        </IonButtons>
      </IonToolbar>
      <IonContent>
        <IonList lines="none">
          {homonyms.map((html, i) => (
            <IonItem key={i}>
              <IonLabel>
                <div
                  className="homonym"
                  dangerouslySetInnerHTML={{ __html: html }}
                />
              </IonLabel>
            </IonItem>
          ))}
        </IonList>
      </IonContent>
    </>
  );
};

export default WordClickModal;
