// apps/taalwiz-web/src/app/shared/word-click-modal/word-click-modal.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
  OnInit,
  signal,
} from "@angular/core";
import { DomSanitizer, SafeHtml } from "@angular/platform-browser";
import { Router } from "@angular/router";
import { ModalController } from "@ionic/angular/standalone";

import {
  IonButton,
  IonButtons,
  IonContent,
  IonIcon,
  IonItem,
  IonLabel,
  IonList,
  IonTitle,
  IonToolbar,
} from "@ionic/angular/standalone";
import { TranslatePipe } from "@ngx-translate/core";
import { addIcons } from "ionicons";
import { playOutline, searchOutline, volumeHighOutline } from "ionicons/icons";
import { MarkdownService } from "../../home/content/markdown.service";
import { DictionaryService } from "../../home/dictionary/dictionary.service";
import { type ILemma } from "../../home/dictionary/lemma/lemma.model";
import { WordLang } from "../../home/dictionary/word-lang.model";
import { SpeechSynthesizerService } from "../../home/speech-synthesizer.service";

@Component({
  selector: "app-word-click-modal",
  imports: [
    IonLabel,
    IonToolbar,
    IonTitle,
    IonButtons,
    IonButton,
    IonIcon,
    IonContent,
    IonList,
    IonItem,
    TranslatePipe,
  ],
  templateUrl: "./word-click-modal.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WordClickModalComponent implements OnInit {
  #router = inject(Router);
  #modalCtrl = inject(ModalController);
  #sanitizer = inject(DomSanitizer);
  #dictionaryService = inject(DictionaryService);
  #markdownService = inject(MarkdownService);
  #speechService = inject(SpeechSynthesizerService);

  clickedWord = input.required<string>();
  word = input.required<string>();
  lang = input.required<string>();
  sentence = input.required<string>();
  lemmas = input.required<ILemma[]>();
  bases = input.required<string[]>();
  safeHomonyms = signal<SafeHtml[]>([]);

  ngOnInit() {
    // Group lemmas by homonym
    const homonymMap = new Map<string, ILemma[]>();
    for (const lemma of this.lemmas()) {
      const key = lemma.baseWord + "." + lemma.homonym;
      homonymMap.set(key, [...(homonymMap.get(key) ?? []), lemma]);
    }

    const safeHomonyms: SafeHtml[] = [];

    for (const lemmas of homonymMap.values()) {
      let first = true;
      const texts = lemmas.map((lemma) => {
        const text = lemma.text.trim();
        if (first) {
          first = false;
          return text;
        }
        // Remove redundant keyword prefix
        const regexp = new RegExp(`\\*\\*${lemma.word}\\*\\*, *(\\d+)`);
        return text.replace(regexp, "$1");
      });
      const homonymText = this.#markdownService.tinyMarkdown(
        texts.join(" ").replace(/;$/, "."),
      );

      const homonymHtml = this.#sanitizer.bypassSecurityTrustHtml(homonymText);
      safeHomonyms.push(homonymHtml);
    }

    this.safeHomonyms.set(safeHomonyms);
  }

  dictionaryLookup() {
    this.#modalCtrl.dismiss(null, "close");
    this.#router.navigate(["home/tabs/dictionary"]);
    this.#dictionaryService.lookup(new WordLang(this.word(), this.lang()));
  }

  canSpeak() {
    return this.#speechService.canSpeakLanguage(this.lang());
  }

  speakWord() {
    this.#speechService
      .speakSingle(this.clickedWord(), this.lang())
      .subscribe({ error: () => {} });
  }

  speakSentence() {
    this.#speechService
      .speakSingle(this.sentence(), this.lang())
      .subscribe({ error: () => {} });
  }

  constructor() {
    addIcons({ playOutline, volumeHighOutline, searchOutline });
  }
}

@if (lemmas().length === 0) {
  <div class="ion-padding">
    <ion-label>
      {{ "common.word-not-found" | translate }}
      <span class="clicked-word">{{ clickedWord() }}</span>
    </ion-label>
  </div>
} @else {
  <ion-toolbar>
    <ion-title>
      <ion-label>
        <span class="clicked-word">{{ bases().join(", ") }}</span>
      </ion-label>
    </ion-title>
    <ion-buttons slot="end">
      @if (canSpeak()) {
        @if (sentence() !== clickedWord()) {
          <ion-button (click)="speakSentence()">
            <ion-icon
              slot="icon-only"
              name="play-outline"
              aria-label="sentence"
            ></ion-icon>
          </ion-button>
        }
        <ion-button (click)="speakWord()">
          <ion-icon
            slot="icon-only"
            name="volume-high-outline"
            aria-label="pronounce"
          ></ion-icon>
        </ion-button>
      }
      @if (bookmarkService.isEnabled()) {
        <ion-button (click)="bookmarkService.toggle(word(), lang())">
          <ion-icon
            slot="icon-only"
            [name]="isBookmarked() ? 'bookmark' : 'bookmark-outline'"
            aria-label="bookmark"
          ></ion-icon>
        </ion-button>
      }
      <ion-button (click)="dictionaryLookup()">
        <ion-icon
          slot="icon-only"
          name="search-outline"
          aria-label="lookup"
        ></ion-icon>
      </ion-button>
    </ion-buttons>
  </ion-toolbar>
  <ion-content>
    <ion-list lines="none">
      @for (homonym of safeHomonyms(); track $index) {
        <ion-item>
          <ion-label>
            <div [innerHTML]="homonym" class="homonym"></div>
          </ion-label>
        </ion-item>
      }
    </ion-list>
  </ion-content>
}

// apps/web-react/src/components/WordClickModal.tsx
import {
  IonButton,
  IonButtons,
  IonContent,
  IonIcon,
  IonItem,
  IonLabel,
  IonList,
  IonTitle,
  IonToolbar,
} from '@ionic/react';
import { playOutline, searchOutline, volumeHighOutline } from 'ionicons/icons';
import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { tinyMarkdown } from '../lib/markdown.ts';
import { useSpeechSynthesizer } from '../hooks/useSpeechSynthesizer.ts';
import type { ILemma } from '../types/models.ts';

interface WordClickModalProps {
  clickedWord: string;
  word: string;
  lang: string;
  sentence: string;
  lemmas: ILemma[];
  onDismiss: () => void;
  onDictionaryLookup: (word: string, lang: string) => void;
}

const WordClickModal: React.FC<WordClickModalProps> = ({
  clickedWord,
  word,
  lang,
  sentence,
  lemmas,
  onDismiss,
  onDictionaryLookup,
}) => {
  const { t } = useTranslation();
  const { speakSingle, canSpeak } = useSpeechSynthesizer();

  const homonyms = useMemo(() => {
    const homonymMap = new Map<string, ILemma[]>();
    for (const lemma of lemmas) {
      const key = lemma.baseWord + '.' + lemma.homonym;
      homonymMap.set(key, [...(homonymMap.get(key) ?? []), lemma]);
    }

    const result: string[] = [];
    for (const group of homonymMap.values()) {
      let first = true;
      const texts = group.map((lemma) => {
        const text = lemma.text.trim();
        if (first) {
          first = false;
          return text;
        }
        const regexp = new RegExp(`\\*\\*${lemma.word}\\*\\*, *(\\d+)`);
        return text.replace(regexp, '$1');
      });
      const homonymText = tinyMarkdown(
        texts.join(' ').replace(/;$/, '.'),
      );
      result.push(homonymText);
    }
    return result;
  }, [lemmas]);

  const handleDictionaryLookup = () => {
    onDismiss();
    onDictionaryLookup(word, lang);
  };

  if (lemmas.length === 0) {
    return (
      <div className="ion-padding">
        <IonLabel>
          {t('common.word-not-found')}{' '}
          <span className="clicked-word">{clickedWord}</span>
        </IonLabel>
      </div>
    );
  }

  return (
    <>
      <IonToolbar>
        <IonTitle>
          <IonLabel>
            <span className="clicked-word">{clickedWord}</span>
          </IonLabel>
        </IonTitle>
        <IonButtons slot="end">
          {canSpeak(lang) && (
            <>
              {sentence !== clickedWord && (
                <IonButton onClick={() => speakSingle(sentence, lang)}>
                  <IonIcon
                    slot="icon-only"
                    icon={playOutline}
                    aria-label="sentence"
                  />
                </IonButton>
              )}
              <IonButton onClick={() => speakSingle(clickedWord, lang)}>
                <IonIcon
                  slot="icon-only"
                  icon={volumeHighOutline}
                  aria-label="pronounce"
                />
              </IonButton>
            </>
          )}
          <IonButton onClick={handleDictionaryLookup}>
            <IonIcon
              slot="icon-only"
              icon={searchOutline}
              aria-label="lookup"
            />
          </IonButton>
        </IonButtons>
      </IonToolbar>
      <IonContent>
        <IonList lines="none">
          {homonyms.map((html, i) => (
            <IonItem key={i}>
              <IonLabel>
                <div
                  className="homonym"
                  dangerouslySetInnerHTML={{ __html: html }}
                />
              </IonLabel>
            </IonItem>
          ))}
        </IonList>
      </IonContent>
    </>
  );
};

export default WordClickModal;
